# Generated by Django 5.2.4 on 2025-07-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kateqoriyanın adı')),
                ('slug', models.SlugField(help_text='Link üçün istifadə olunacaq unikal ad (məs: elektronika-mehsullari)', max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Üst Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Məhsulun adı')),
                ('slug', models.SlugField(help_text='Link üçün istifadə olunacaq unikal ad', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Şəkil')),
                ('description', models.TextField(blank=True, verbose_name='Təsviri')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət (AZN)')),
                ('stock', models.PositiveIntegerField(verbose_name='Anbardakı say')),
                ('available', models.BooleanField(default=True, verbose_name='Satışda mövcuddur?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ['-created_at'],
            },
        ),
    ]
