# Generated by Django 5.0.1 on 2025-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (məs: fas fa-heart, fas fa-laptop, fas fa-tshirt)', max_length=100, null=True, verbose_name='Icon Class'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_color',
            field=models.CharField(blank=True, default='#007bff', help_text='Hex rəng kodu (məs: #ff0000)', max_length=7, null=True, verbose_name='Icon Rəngi'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='32x32 və ya 64x64 ölçülü PNG/SVG icon', null=True, upload_to='category_icons/', verbose_name='Custom Icon'),
        ),
    ]
