# Generated by Django 5.0.1 on 2025-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon_class_category_icon_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_color',
            field=models.CharField(blank=True, default='#007bff', help_text='Hex rəng kodu daxil edin (məs: #ff0000 qırmızı üçün)', max_length=7, null=True, verbose_name='Icon Rəngi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='32x32 və ya 64x64 ölçülü PNG/SVG icon yükləyin', null=True, upload_to='category_icons/', verbose_name='Custom Icon Şəkil'),
        ),
    ]
