# Generated by Django 5.0.1 on 2025-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_icon_color_alter_category_icon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Kateqoriya', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, help_text='Kiçik rəqəm daha yuxarıda görünür (1, 2, 3... şəklində)', verbose_name='Sıralama'),
        ),
    ]
