# Generated by Django 5.0.1 on 2025-08-08 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='0 = ən yüksək priority, böyük rəqəm = aşağı priority. Header-də bu sıra ilə göstəriləcək.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Priority (Sıra)'),
        ),
    ]
